### ISSUE TITLE
How do you find / make time to stay productive?

### ISSUE THREAD

**Issue by RyKilleen** [SeanKilleen/ama#12]
Do you find it's a mindset? Scheduling tricks?

Finding energy and motivation for extracurriculars is often an issue of mine. I'd love to hear more about how you can manage to burn the candle at both ends

**Comment by SeanKilleen** [comment]
@RyKilleen honored to get this one from you, because I think you're pretty productive.

## First up, an Important Point: Sometimes I don't.

And that has to be OK.

In general, I feel very good about my productivity level and the things I'm able to produce & get done. That said, sometimes it's just not there for whatever reason.  I'm not saying I completely give up in those instances, but I allow the space for it to pass, and I forgive myself for having an output that is below what I may have expected. I'm a human, and if I don't pause and remember that every so often, I don't think it would wind up well for me.  So sometimes my biggest trick is letting myself off the hook occasionally when it doesn't go well.

That said, I'll try to place some tips below.

## Find Whatever system maps to your brain, and use it
Different tools might work for you at different times, or depend on how you currently are thinking about things.

* I started with RememberTheMilk, way back when. I liked the way I could categorize & tag things, and build smart lists that helped me try to surface what I should do next.
* I have a lot of different contexts, so I switched to Trello where I could have different boards, and also I could map my brain's understanding of what the workflow is for those boards. My mind is busy and usually forgetful so I try to dump things into Trello.
* Sometimes, Trello is too much and it feels like a sea of tasks and I just need to get through the day. That's when I'll look at Trello, and copy things on to a piece of paper, because I need to physically cross things off.
* Sometimes, that list doesn't feel like it has the physical movement I need, and I'll try to switch to stickies to get things done.
* And sometimes, I have to step back and say "holy crap I'm spending way too much time in meta-world organizing my brain".

I've done enough various cycles of this that I've started to learn where my brain is and meet it there. Which brings me to my next point...

## Try to give yourself multiple access points for your motivation/energy

This takes a while, is easier said than done, and usually involves a lot of self-discovery. 

I know that on a given day, I will be potentially motivated by several types of things:

* Coding
* Writing
* Deep thinking
* People skills / connections 
* Ideation / divergent thinking 

Luckily, I'm in a space where I'm usually able to be productive around one of those things. So my key is -- I try to always have at least one item in my queue/backlog that I can map to a motivation. If I have some coding stuff on my plate but am really motivated by writing that day, maybe I'll try to bang out some e-mails or give myself space in the morning or at lunch to map out a blog post. If I need to be thinking about strategy or business development but I have an urge to code, I'll let myself deviate for a bit to scratch that itch.

Honestly, the jury's still out for me on whether this is a good thing or not. I tend to produce a lot of stuff and get things done, but going where my energy takes me often means that I may produce less overall results in terms of deep impact (though I've usually been able to produce that as well). But, that leads me to my next topic...

## Find your Impacts and Dive in

In the last section I talked about not knowing if I'm as impactful as I could be when I just follow my energy. This is different in one big way: If there's a major piece of impact in front of me, or something where I think I can really move the needle, I will throw my whole self at it. There, my energy tends to focus around the impact I can make. Can I really help open a client's eyes to some technology or technique? All of a sudden I'll have no problem coding up a sample, doing a power point, and writing up documentation around it. The impact itself becomes my energy, and I start firing on all cylinders, because I feel like I have an opportunity to really effect some serious change. 

These are the best days.

I think this concept is sort of what the book Essentialism gets to -- if I was to strip away all those smaller things I'm doing when I go where my energy takes me, would that maybe leave room for even greater impact? If I didn't have so many different contexts on my plate, could I go deeper on things? Almost certainly. Finding the impact takes time, and I haven't necessarily figured out how to spot it all the time. But when I do...oh man, it's _on_.

## Give yourself space for the meta-work

I often forget this, and every time I remember it, I feel like I have a better day. Making space to map out my day and what I want to try to accomplish during it is really important. I often get swept up in what's happening, or a deluge of e-mails & requests, and I forget about this (see the previous section). I've tried adding a calendar event as a reminder to set up my day before I jump in. Some days work better than others. But I find if I can take 5-15 minutes to set my own goals for the day and try to start with one of them, it goes a long way.

## Balance doesn't mean 50/50 (at least for me)

This is for better and worse -- especially when taking into account a marriage, etc. -- but my work/life balance is something that other people would probably say is _way off_, certainly at times. I have found work in an industry that constantly piques my curiosity, teaches me things, allows me to create, and presents fun and challenging problems in need of solving. So it's my hobby too. This is not the case for many people -- nor should it need to be. But a key helper on my productive days, I think, is that I love what I do and I feel like I get to bring my whole self to it. This means that I'm more likely to "leave it all on the field". This balance is as problematic for me as it is helpful, but one thing is for sure -- it's my balance, and your mileage will vary. 

Finding and understanding where your balance is, and basing your own productivity off of that target, is a really important part of finding a good pace for yourself instead of keeping up with others. 

## Wrapping up

I think it's interesting that you said "burn the candle at both ends". This sounds like something you're looking to emulate -- but it's generally a negative idiom. Burning the candle at both ends means one is exhausting oneself, trying to do too much, and ultimately running out of finite resources (the candle, one's life) twice as fast. 

I think the key is more to understand what keeps your candle built up, and what increases or decreases the burn rate. I feel like it's a lifetime to figure out that balance, and I'm nowhere near having it figured out. But trying to figure it out has yielded a lot of positive results for me.

## Follow-up?

Happy to elaborate on anything here. Also, you know where to find me, because you are literally my brother. (and an excellent and productive one at that.)
