### ISSUE TITLE
Talk where you don't know who the audience is

### ISSUE THREAD

**Issue by triplee78** [SeanKilleen/ama#13]
Say you're prepping for a talk at the MeetUp or company brown bag level (although this probably applies at a conference too), and you're no sure entirely who the audience will be, or how big it will be, save for members of the community.   How do you prepare? Is there anything you do differently?  Bonus points for tips on how to prep for a mix of on site and remote audience simultaneously.

Thanks!

**Comment by SeanKilleen** [comment]
Hey @triplee78! Cool to see a question from you here. :) I'll try to answer as best I can.

## Remote or Not?

* One piece of advice I can give is that if part of the audience could be remote, you should construct the talk for those people first and assume the entire audience is remote. This will make sure you don't fall into certain traps (e.g. bringing a physical illustration to the talk when the audience might only see slides). 
* If you are going to allow input from the audience or take questions throughout, it's great to utilize a tool to allow participants to enter and queue questions as well (and if possible, encourage the physical audience to use those mechanisms too). This way any feedback or questions are blended together, which helps any remote audience feel that much more connected to you.

That said, I'm always grateful when there are at least _some_ live humans in the audience. My experience with webinars is that they're far more difficult for me personally because I get super in my head during a presentation when I can't see one or more human faces to talk to.

## Not Sure How Big the Audience Will be?

* One thing I've noticed for myself: if I know the audience might be bigger, I try to really practice what I'm trying to say. Normally I do this regardless, but I try to do it extra when I know it will be a big crowd. This doesn't just have the benefit of helping me get the presentation to a better place; it also prepares me to speak more clearly. When I know what I'm going to say, allows me to project it better and more confidently. Otherwise, I find myself talking toward myself a little bit more, or stumbling a little bit, which I think causes a disconnect in larger audiences.
* On the flip side, if you think your audience might end up being super small and intimate, I try to have some component of interactivity (maybe it's a question that everyone could likely respond to, something slightly conversational that you veer off on for a point, or preparing to take questions throughout). This way, if for some reason it's a small crowd, I can make the talk feel or seem less robotic.
* No matter what, the energy you bring matters. No matter the size of the crowd, make sure that you're prepped to be enthusiastic and help others be enthusiastic about what you're speaking about. If you're speaking about it, it generally is important to you -- help others feel the awesomeness of your topic. That will come across no matter what size the crowd is.
* Make your slide text bigger. No, bigger still. Bigger than that. Only a few words and major concepts on the slides. It feels terrifying at first (at least it did for me), but there are still speaker notes if you blank, and you know the topic. I find this also helps my topic. The more I break down slides, the more I know how much time each section / topic will take. It also gives you the opportunity to swap out a word or phrase with a fun picture / meme, which I find tends to go over well (or my audiences are just kind). Lastly, if I break down my slides well, they serve as a sort of "stream" for me. If I feel lost, I can use the next slide to step back into the stream, which helps me remember what I want to convey and get the groove back.

## Not Sure Who the Audience Will Be? 

I think this is probably the *most* tricky one to encounter. The hard part here is that if you don't know who they'll be, you won't know what skill level they have and if it's scattered it could be hard to "on-board" folks into the world of your talk / presentation. 

* This is less of an issue when the topic is meant to be more of an introduction or overview, because you can prep the audience by making it clear that it's the case. If you bring that to folks' attention, they usually appreciate it. And it also means that you can comfortable assume the same baseline that everyone is new to the topic. 
* If the topic is more of 200-300 level topic, figure out what questions you can use to gauge the audience, and ask them via a show of hands / on-line poll before or at the start of the talk. Try to structure your talk from beginner to advanced. If you've got an advanced class who seems familiar & confident, go faster through the beginning talk. If you have a beginner crowd, insert a copy of your closing/ending slide at the end of the beginner portion, so that you can stop there without folks feeling like you fast-click through 30 more slides they didn't get to see.
  * Note: this isn't always possible, I know. Some talks don't flow that way. If you can't structure it that way, I'd do your best to make it as accessible as possible given what you know about the audience.

## The Bottom Line: Decision Trees + Improvisation

The key here, honestly, is that you're asking the questions and considering them. It's far less important for your talk what people generally do, and likely far more important is you thinking through what _you'll_ do, _ahead_ of time. Having that decision tree in place -- knowing what you want to do in these scenarios should these things arise -- saves you from trying to think through it in real-time during a talk (which has never worked well for me personally).

Also, improv is a big component. The more comfortable you feel about a topic and the more times you've spoken about it, a lot will go on auto-pilot and the rest of you starts to relax and feel freer to tailor the material and make it more like a conversation. You'll be able to have a few tangents, slide between topics more easily, and adjust the feel because the material & delivery won't be a consideration. That's a really cool spot to get to with a talk, and it takes time.

If it's the first time you're delivering a talk, also remember you have valuable things to say, an audience that (hopefully) isn't forced to be there, and you're trying to help people navigate something they may not be familiar with. Your audience, in almost all cases, is rooting for you and wants you to succeed. So, just by agreeing to do the talk, you're almost guaranteed to help someone with something. Don't forget to count it as a win that you're even stepping up to do the talk.

____

I'm not sure I 100% addressed your question, but I'd be happy to follow up on any subsequent questions / off-shoots of this. Either here, or you know where to find me! 😄
