### ISSUE TITLE
What are your short and mid term career goals

### ISSUE THREAD

**Issue by gxespino** [SeanKilleen/ama#14]
Two parts:

- Goals for Q2-Q3 2019
- Goals for 2-3 years out 

Boom! You said anything so there ya go @SeanKilleen

**Comment by SeanKilleen** [comment]
Hey @gxespino! Thanks for dropping a line.

Indeed, I did say anything :laughing: and this is actually a great question to grapple with, because I'm very productive but also *terrible* at defining goals. I find that a lot of my progress comes from defining outcomes, figuring out multiple ways to move toward those outcomes, and then following my energy. This only takes me so far though, and having some notion of goals is important. So I'll do my best below, reflected in my current thinking:

## Remainder of 2019

* **Balance**: I recently wrote about [the revelatory experience of taking 2 weeks off for my honeymoon](https://seankilleen.com/2019/06/what-i-learned-from-taking-a-two-week-vacation-for-my-honeymoon/). One of the things this taught me is that balance and presence is a muscle memory that has to be worked on. I want to capture this momentum for the remainder of 2019 and focus on it.
* **Essentialism**: I want -- no, need -- to say no to a lot of things, even if I *could* do them. I have an opportunity to make a larger impact, but not if I jump at everything that is in front of me. I'm trying to come up with a personal framework to run these things through to help me ruthlessly prioritize.
* **Revise my abstracts**: I submit to a lot of conferences and I don't think my catalog of talks fully expresses the subject matter and impact of those talks. I want to more meaningfully craft those messages and expand what I can offer.
* **Write more regularly**: I have a lot of things I want to talk about, and I'd like to write on a more regular cadence.
* **Fall in Love with finishing things**: I'm too in love with starting things, so pursuant to the above, I need to start to love finishing them. Too many ideas, not enough check marks.

## Goals for 2-3 years out

* **Reach Principal or Fellow level in an organization**: I believe I'm ready to contribute more broadly to a company's success and culture and that I can positively impact things at that level. I don't mind leading from wherever I am, but a big goal for me is to reach that level of recognition and reach in an organization I'm proud of.
* **Deliver a product**: I have the ability to produce things that help people and I want to see one of my own validated ideas through to completion, in production, benefitting someone.
* **Become more widely known and respected in my communities**: we're being honest, right? I want to be known as a guy who knows what he's doing, has knowledge, gets things done and (most importantly) cares about people. I want this to be true both online and offline
* **Grow/re-grow personal relationships**: I suck at keeping in touch with people and tending relationships. It's always an unintentional afterthought, but it has the predictable side effects. I want to invest more in that area for a richer life beyond goals.
* **A book?**: I've always wanted to write a book, and the outline for it is starting to take shape and solidify. That's a big undertaking and I'm not sure if I'm ready to make it an official goal yet, but it's on my mind as I look toward the future.

Subject to change :wink: but those are my thoughts at the moment. Thanks for helping make the space for me to think through it!

**Comment by SeanKilleen** [comment]
@gxespino also, feel free to continue this discussion if I didn't answer or you want to go deeper. 👍
