### ISSUE TITLE
C# coding question

### ISSUE THREAD

**Issue by ctyar** [SeanKilleen/ama#16]
I hope it's ok to ask technical questions.
I don't have anybody to ask these types of questions and I saw your tweet so...
Can you please take a look at this question at Stack Overflow.
https://stackoverflow.com/questions/62081141/mark-a-property-as-non-null-based-on-another-properties-value

**Comment by SeanKilleen** [comment]
Hi @ctyar! Thanks for reaching out. I certainly don't mind a technical question -- the last "a" in AMA is for"anything", after all. 😄 

Firstly, I'm sorry your question got down-voted. While the question could be clearer, I don't like when it's down-voted without a good explanation. 

Upon looking at the question, I think there are a few ways to approach this problem:

* **Treating it as a compile-time problem**. This is in line with what you're asking, but could require a slightly different approach.
* **Treating it as a validation problem**. This is where you'd use a validator to validate the instance of your type before using it elsewhere. 
* **Treating it as a type expression problem**. This is where you'd express the fact that this code may or may not have a value, and you express that via the type system.

I'm a bit swamped right now so I can't dig into the specific details of each -- keep an eye out for some follow-up comments that I'll make here. 

What I will say is that rather than performing compiler gymnastics to guarantee this, I might prefer instead to make it explicit. Rather than using a `bool UserHasValue` and a `User? User`, you may want to consider [thinking about it as a `Maybe<User>`](https://blog.ploeh.dk/2018/03/26/the-maybe-functor/). This indicates to everyone who accesses this code that there may or may not be a user here, and that they should check for it. There are libraries to achieve this and you can also build your own `Maybe<T>` type pretty quickly.

Similarly, if having a `User` present is what is required for that class to be valid in a certain context, you may want to [use FluentValidation](https://fluentvalidation.net/), create a `MyClassValidator : AbstractValidator<MyClass>` class that defines a `RuleFor(x=>x.User).NotNull();` and then you can validate that class in your processes. This would most likely be useful if there are a number of these sorts of validations that you're doing.

I don't know the answer off-hand to the nullable reference type question that you're asking, but I'll work to see if I can figure it out as I've been looking for an excuse to play with nullable reference types more anyway. :) Stay tuned!
