### ISSUE TITLE
How did you become a Microsoft MVP?

### ISSUE THREAD

**Issue by antmdvs** [SeanKilleen/ama#17]
What does it take to be an MVP? Is MVP a stepping stone to working at MS? How else does it benefit your career?

**Comment by SeanKilleen** [comment]
Hi @antmdvs, thanks for writing! This is an interesting question because it has a lot of angles and is bound to be personal and contextual. Microsoft has a lot of MVPs operating across a wide variety of areas, so I can't presume to speak for others or for the program officially.

I'll try to take your questions one at a time.

## How did you become a Microsoft MVP?

There are multiple, answers to this one -- all of them likely true to some degree:

* Someone nominated me, others agreed I had potential, and I went through a process of detailing contributions I'd made to the community in the past year. Then, a committee consisting of folks at MS agreed I'd met the contribution threshold for being an MVP, and gave me the award. 
* I believe a few existing MVPs may have put in a good word for me throughout the process. These are people I've interacted with for some time, over the course of years. I know a few people who sent multiple messages, and I'm grateful.
* Last year, I [was almost elected to the .NET Foundation Board of Directors](https://seankilleen.com/2019/05/that-time-almost-became-dotnet-fdn-board-member/) because my vision for the Foundation resonated with a lot of people (this year [I decided not to run](https://seankilleen.com/2020/06/thoughts-on-the-net-foundations-revised-election-process/)). I think running for the Foundation and the platform I presented raised my profile a little bit more.
* People knew me, or are starting to know me, because I've [spoken at a lot of events](https://seankilleen.com/Talks/), which again raised my profile a bit.
* Lastly, I care about the community a lot. I'm continuously trying to get involved, blogging, speaking, contributing to projects, and attempting to be a good and thoughtful developer citizen in the .NET space.

Who's to say how much each of those items factored in? I can't know. I have no idea if there's a formula, as this is the first time I've received the award. We'll see how next year goes; between a pandemic and being a new dad, my bandwidth for contributions has been significantly limited.

My perspective on it is to treat it as additional validation of the effort I've put into caring about the .NET community. It was wonderful to know that this was noticed and that others found it valuable enough to receive the designation. It is a wonderful feeling. There are plenty of people who deserve to be MVPs who aren't. And if I'm not renewed next year, I'd be sad but it also wouldn't stop me from contributing to the community, blogging, etc. -- I love this stuff.

To say I didn't seek it isn't quite right. For a long time, I hoped it would just happen. But when I realized I had to be nominated, I mentioned to a few people that I was interested in the program. Some thought I was already an MVP (a nice feeling!) but others understood that the process has to be initiated.

## What Does it Take to be an MVP?

* I think one of the things I've seen is that it's a bit of a black box. 
* I know part of it is the overlap with Microsoft's interests and the audience one reaches. (they're a company after all; there's _something_ in it for them. And that seems reasonable.) 
* I think it takes a commitment to be out there and contributing to the MS and MS-adjacent ecosystems. I've seen people who were fantastic contributors to forums, people who blog and speak, people who maintain popular and/or important OSS projects, people who provide continual amazing product feedback, people who have been a force for great strides forward in the world of .NET -- all receiving designations. Now add to that the fact that there are Office MVPs, Azure MVPs, Developer Technologies MVPs, etc. and there are a lot of paths to potentially get there.

To summarize, I'd say: It takes putting yourself out there in an effort to help others within this ecosystem.

## Is MVP a stepping stone to working at MS? 

That's hard to say. It hasn't been for me, at least yet. 😄 One thing that's important to note is that you can't be an MVP and work at Microsoft; you'd have to give it up the designation order to do so. 

I think it's healthy for there to be a large group of people outside of Microsoft who are heavily invested in the ecosystem (and in making it better for everyone.) So I don't think the MVP program is necessarily a recruiting avenue for Microsoft. However, the other aspect is that MVPs tend to be known more by Microsoft and interact more with people from Microsoft, so there are opportunities there to connect and I assume sometimes job opportunities are an artifact of those connections.

## How Else Does it Benefit Your Career?

I'll have to return to this AMA in a few years to answer, I suppose. 😄 Some immediate benefits:

* Access to product licenses for things I'd otherwise have to pay for (lots of dev tools offer free licenses to MVPs)
* Access to a large community of MVPs who care about the ecosystem as I do and who are usually very bright and lovely people. 
* Direct interaction with product teams to provide feedback and have issues addressed.
* A jump on many announcements and new initiatives before they become public. This allows me to stay relevant in a much easier way, and allows me to help shape client strategies even when I can't reveal specific information. Very useful in consulting.
* It opens doors. I've seen an uptick in social activity since becoming an MVP. I also tend to think MVPs are given consideration by default around things like speaking engagements. 

My hope is that it benefits my career by making it easier to help others and contribute to the community, and helps folks recognize that I'm already committed to doing so.


-----

Let me know if you have any questions or follow-ups! I'll close this issue now to archive it, as I do after I answer any question here. 👍

**Comment by antmdvs** [comment]
@SeanKilleen Thanks for the thoughtful and informative response as well as your contributions to the community. I saw you speak at CoTB 2018. Hope to see you there again someday. Congratulations on the award and becoming a dad!
