### ISSUE TITLE
How do we collectively improve our Zoom experience?

### ISSUE THREAD

**Issue by matthewdeanmartin** [SeanKilleen/ama#20]
Are we doomed to a choice between a bad conference call vs having to go into the office for a decent meeting or are the technological, social solutions to whatever it is that makes zooms sometimes unsatisfactory (low participation rates, esp).

**Comment by SeanKilleen** [comment]
Thanks for writing, @matthewdeanmartin! Sorry I'm just getting around to this now; I did that thing where I keep trying to make a post complete rather than...you know, posting it. You'd think I'd have learned by now! 🙄 

Off the top of my head, I think there are a few dimensions to this problem. I'll try to think address it using the the lens of culture ("who do we want to be?"), strategy ("what do we want to achieve?") and tactics ("How do we work?")

## Culture (who do we want to be?)

Despite workers driving productivity and profitability for an organization, many organizations are not set up to prioritize their employees' time. Similarly, the cultures are often highly centralized command-and-control cultures that believe that brilliance and results originate from management and trickle down to those who execute.

As a result, most meeting cultures at organizations are ...also terrible. Meetings are a default way of working because of the perceived necessity of the flow of information, and the way the organizational structure conceives of success.

This cascades into strategy.

So, at a cultural level, suggestions I have would be:

* Prioritize employee time outside of meetings, where they have space to think deeply and accomplish work.
* Empower people to do work and broadcast their intentions and to radiate status, rather than constantly querying.
* Create more information about problem spaces and invite others in to contribute their thoughts on execution (that one actually makes for some pretty engaging meetings)

## Strategy (what do we want to achieve?)

So many meetings, remote or not, are called for the wrong reasons. Status updates, decisions by committee, touch points to keep things moving, coordinating work across siloed teams, etc.

I love ["Read This Before Our Next Meeting" by Al Pitampalli](https://www.amazon.com/Read-This-Before-Next-Meeting/dp/1936719169). It's a great quick read that helps anyone within an org get buy-in for rapidly increasing the value of meetings. It describes valid meetings as 1) brainstorming sessions or 2) meetings about how to support a decision that has already been made. It also has great tips on a "contract" of sorts for meetings, which I'll badly paraphrase from old memory -- start on time, even if you're the only one there; no goal? no meeting; add preparation materials and don't join unless you're prepared; end on time or early, no matter what; draft notes along the way and send them immediately after; anyone can opt out of a meeting that they don't add value to or get value from; etc. etc. 

At the strategic level, I suggest:

* Being ruthless about whether meetings are merited. If they're not, cancel them until it's clear they're needed. Avoid recurring meetings unless the value is crystal clear.
* Finding what the value proposition of a meeting is, and seeing if there are better ways to achieve it. You've inspired me to publish a draft blog post about shifting meetings to the left; I go more into detail there on examples.

## Tactics (how do we work?)

I haven't explicitly addressed your zoom meeting concern yet, but that's because I think a lot of energy that could exist for good meetings is instead taken up by shortcomings at the cultural and strategic level. These things are higher impact to address. 

With that said, some tips for how to work virtual meetings IMO:

* Make a tiny time for socializing: this one is tough for me because I typically think (and my advice above would lead one to believe) that we should jump right into meetings. But we're in an extended pandemic and in many cases people have been starved for human interaction and camaraderie. Any small icebreaker, celebration, or moment of human vulnerability you can facilitate will be well worth it.
* Invest in training and reading about facilitation. Depending on the desired meeting outcome, there may be engaging ways to facilitate it.
* Don't forget about the value of things like live polls. Menti and PollEverywhere and Mural add interactivity to remote meetings

## Don't Forget Psychological Safety! 

One last point -- make sure everyone feels comfortable before beginning a meeting. A great way to do this is with [a safety check](https://www.funretrospectives.com/safety-check/). Take an anonymous poll or have people throw stickies out there indicating how safe they feel sharing their true thoughts in the discussion. If it's not a "safe" environment for everyone, cancel the meeting & meet with individuals to fix that first. IMO it matters more to good meeting outcomes than almost anything else.
