### ISSUE TITLE
Questions about your blog

### ISSUE THREAD

**Issue by benpetersen** [SeanKilleen/ama#3]
- How do you get ideas for your blog posts?
- You mentioned, writing posts that are helpful for people going to meetups (level up on x), how do you leverage that thought process in a blog where you don't know the user base? Do you write about your experience? Or just things that excite you and not your day to day. Any insight would be helpful
- Do you believe in posting once a week or more?
- Why did you decide not to have code in your posts?
- Why does your homepage purposefully limit posts to 5? Is there any SEO downside to this or UX upside?
- Have any ideas for my blog [benpetersen.github.io ](benpetersen.github.io)? It's a work in progress and I'd love some tips.

**Comment by SeanKilleen** [comment]
Hi Ben! These are a bunch of great questions. I’ll try to tackle them here as best I can on a first pass.

> How do you get ideas for your blog posts?

I am someone who tends to have a lot of things pop into my head, and I have trained myself to trust that they probably have some merit. So, I try to capture every “huh” moment (my term) that I have. If I have an idea that makes me say “huh!”, I write it down. If I have a question that makes me say “huh?” I write it down. If an observation makes me say “huh.” I jot it down. Not nearly all of these are winners, but it reminds me to take stock of my observations, and the blog posts become about sharing those observations or questions with others. 

Also, if I think something is awesome, that’s usually a good indicator that it’s worth writing about.

> You mentioned, writing posts that are helpful for people going to meetups (level up on x), how do you leverage that thought process in a blog where you don't know the user base? Do you write about your experience? Or just things that excite you and not your day to day. Any insight would be helpful

When trying to think of my audience, sometimes I assume the audience is me. I’m dropping some tips for myself to come back and read later. I’ve come back to a number of my “quick tip” posts and also seen them pop up in some of my own future google searches. 😄 

For posts that aren’t inherently for me, I try to think about what’s required to understand the post and indicate it in the title or mention it up front.

I also ask for feedback and sometimes folks make use of it, which is fantastic. So if something goes over someone’s head or I get a lot of questions, that’s a good indicator of a need to revise — or even for a follow up post.

In general, I assume my audience to be smart, good people who are interested in learning or solving a problem. No matter what level you write for, there’s someone out there who can use it to “level up”.

> Do you believe in posting once a week or more?

I believe that it’s helpful, and I also believe that it’s really hard to keep up. 😄 I would love to blog once a week or more, but oftentimes life gets in the way and a backlog grows. However, the rhythm of expressing yourself regularly makes it a lot easier to keep going, and the momentum is a powerful thing if you can build it up. I also find that writing more often helps me express things more clearly in real life, and forces me to take my time a little bit more, which helps me out.

So, it’s worth building up that writing muscle, but don’t guilt yourself if you fall off for a bit.

> why did you decide not to have code in your posts?

I actually do have code in some of my posts. 😄 I think it’s fine when called for. I don’t focus on it exclusively because I think there’s a lot of value in concepts, and also because the type of writing / thinking I’ve been doing for a bit is more conceptual. There’s a big backlog of posts, many of which will make good use of code. They also take longer to write for me, and thus incubate for longer.

> Why does your homepage purposefully limit posts to 5? Is there any SEO downside to this or UX upside?

When I first moved to github pages , I didn’t know Jekyll (my blogging engine), so I chose a theme written by someone else to get started 😆 that’s the entirety of why it’s like that. I wish I could tell you that more thought went into it, but nope.

> Have any ideas for my blog benpetersen.github.io ? It's a work in progress and I'd love some tips.

I’ll take a look and if I have any feedback, I’ll post it on your repo!
