### ISSUE TITLE
Is coding a young person's career?

### ISSUE THREAD

**Issue by matthewdeanmartin** [SeanKilleen/ama#5]
Where will a typical coder career be its last third?

**Comment by SeanKilleen** [comment]
@matthewdeanmartin just seeing this now, sorry! 

Could you clarify the body of the question? I'm not sure I understand the phrasing, though I'm very interested in speaking to the subject.

**Comment by matthewdeanmartin** [comment]
First third of one's career, 22-35 Junior to Senior developer, lots of typing. 35-48 Tech Lead, Scrum Master, Developer with a longer beard. 48-62 ... where did all the developers go? I mean, I hardly ever have people on my team in this age bracket. They can't all have become CTOs.

Scott Hanselman in one of his podcasts mentioned that after a few decades of coding your wrist start to hurt. Everyone talks about the risk of getting one year of experience 20 times over and becoming unemployable. Not everyone can be promoted to management and worse, IT attract the sort of people that *don't* want to be in management.

Developers are a smart lot of folk, I imagine there are some optimistic answers.

**Comment by SeanKilleen** [comment]
Hi Matt,

I think this is a really good question and have been thinking on it. I'll try to see if I can touch on everything a little bit.

I've been grateful for anyone I've gotten to work with who's in that third bracket; they've leveled me up more than I could have hoped, every time, without fail.

### First off: I hope not!

I hope be coding & creating for a long long time, and we need senior people in our industry who can share their experiences & help the industry mature.

### Anecdotal: It can be done

My Dad falls toward the upper end of your suggested third bracket. I recently followed along as he built a brand new product, from scratch, that is disruptive for his industry, and involved 3D graphics from JavaScript and the latest in .NET, deployed to Azure.

### ...if you love the work & keep doing it

That said, I think a lot of folks start off with a strong affinity for coding as an act of creation. 

Over time, they may follow the manager's path and move away from coding as an act of creation, toward driving larger value or helping teams succeed. 

Also, if you're doing maintenance only (as so much software is), and you aren't able to find a way to make that interesting, then the spark of creation might fade over time, leading also to a dulling of the profession and a desire to move away from coding or from the industry in general.

### ...And your company or other BS doesn't get in the way

As you mentioned, sometimes companies don't allow for growth paths for coders in any way other than management. I think that without an alternative path, that's a great way to lose a lot of fantastic coders. My current employer does a pretty good job of trying to mitigate this I think. They have a management path for sure, but they also have a technical expertise path. And you can do a little bit of both. That kind of organizational / structural flexibility is hugely important for growth and a rewarding career, I think. 

Separately, sometimes company culture wears people down over time. If there's a ton of bureaucracy and everything is a fight, over time, coding becomes a struggle that is fraught with challenges that have nothing to do with coding. So of course people would lose their passion for coding & fade from it over time.

### ...And you're willing to keep up with things

We know as devs that it's easy to stagnate. Technology moves on, paradigms evolve, and if someone doesn't keep up their skills (and a company doesn't make space for them to do so), over time their skillset may become misaligned with coding, even though they're still a perfectly fine coder in general. I imagine this would make it harder to stay in the occupation of coding.

### ...And you're willing to carve a path

Given the above and how hard it is to step out of that flow, it also takes more energy to stay on that path -- and I wouldn't blame anyone for choosing to put their energy elsewhere. At some point, you don't want to be job hopping to find that stability and you don't want to spend the energy to fight the inertia, because the craft might not be the primary focus of your life (which is totally OK).

### If a Dev codes in the forest, and nobody sees them...

I also think that we may suffer a visibility bias on this in some cases. Due to life flexibility, energy, priorities, etc. we often see a lot of younger people doing the "extra" things -- blogging, speaking at meetups & conferences, OSS projects, side gigs. So they seem much more visible.

A lot of the excellent devs I've seen in the "last third" that you mentioned do little or none of these things. Doesn't mean they don't exist. I think many of them may evolve into Hanselman's "9-to-5 developer", building good code for their company but not doing much beyond that (which is, again, totally OK). 

_____

I'm not sure that answers your question, but that's the thoughts I've got on it right now. Happy to continue the discussion. :)

(closing per the process because it's "answered" but no reason we can't keep talking)
